# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c587e817e726e5e12ec9fc16a39bc36c1b03046f79b5feea8cd6cab0ba6c3fee2305538b2ee5c6d7707084058dcb903d218d5a470d2b846602cde3e9a85f4ed0

test:
  secret_key_base: fe39eba76fcda4363b7069d88eb6b458bc77b6cd1d5f23219aff3b0d53b07402d903f3265e6ded16620176d36921a6a5398451f10b29a97f247b92cd1d2f5378

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
